name: py311-nix-colab
channels:
  - conda-forge
dependencies:
  - python=3.11.11
  - pip>=24.0
  - pip:
      - tensorflow[and-cuda]>=2.15.1
      - tensorflow-addons[tensorflow]>=0.14.0
      - tensorflow-datasets>=4.9.2
      - tensorflow-hub>=0.16.0
      - opencv-python>=4.7.0.72
      - matplotlib>=3.5.0
      - ruff>=0.0.271
      - yapf>=0.33.0
      - isort>=5.12.0
      - pandas
      - loguru
      - ipython
      - pyright
